on:
#  push:
#  pull_request:
workflow_dispatch:

jobs:
  build:
    name: "Build Metropolis"
    runs-on: ubuntu-latest
    steps:
      - 
        name: "Checkout Repo"
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - 
        name: "Setup Python"
        uses: actions/setup-python@master

      -
        name: "Install requirements"
        shell: bash
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - 
        name: "Run build.sh"
        run: ./build.sh
        shell: bash

